elCicdTemplates-resourceQuotas:
- templateName: resourceQuota
  appName: small-mem-quota
  anyProfiles:
  - small-mem-quota
  namespaces: ${small-mem-quota_NAMESPACES}
  hard:
    limits.memory: 12Gi
  scopes:
  - NotTerminating

- templateName: limitRange
  appName: small-mem-limit
  anyProfiles:
  - small-mem-limit
  namespaces: ${small-mem-limit_NAMESPACES}
  limits:
  - default:
      memory: 256Mi
    max:
      memory: 1Gi
    defaultRequest:
      memory: 50Mi
      cpu: 150m
    type: Container

- templateName: resourceQuota
  appName: small-storage-quota
  anyProfiles:
  - small-storage-quota
  namespaces: ${small-storage-quota_NAMESPACES}
  hard:
    requests.storage: 24Gi

- templateName: resourceQuota
  appName: medium-mem-quota
  anyProfiles:
  - medium-mem-quota
  namespaces: ${medium-mem-quota_NAMESPACES}
  hard:
    limits.memory: 48Gi
  scopes:
  - NotTerminating

- templateName: limitRange
  appName: medium-mem-limit
  anyProfiles:
  - medium-mem-limit
  namespaces: ${medium-mem-limit_NAMESPACES}
  limits:
  - default:
      memory: 512Mi
    max:
      memory: 2Gi
    defaultRequest:
      memory: 50Mi
      cpu: 150m
    type: Container

- templateName: resourceQuota
  appName: medium-storage-quota
  anyProfiles:
  - medium-storage-quota
  namespaces: ${medium-storage-quota_NAMESPACES}
  hard:
    requests.storage: 256Gi

- templateName: resourceQuota
  appName: large-mem-quota
  anyProfiles:
  - large-mem-quota
  namespaces: ${large-mem-quota_NAMESPACES}
  hard:
    limits.memory: 96Gi
  scopes:
  - NotTerminating

- templateName: limitRange
  appName: large-mem-limit
  anyProfiles:
  - large-mem-limit
  namespaces: ${large-mem-limit_NAMESPACES}
  limits:
  - default:
      memory: 1Gi
    max:
      memory: 4Gi
    defaultRequest:
      memory: 50Mi
      cpu: 150m
    type: Container

- templateName: resourceQuota
  appName: large-storage-quota
  anyProfiles:
  - large-storage-quota
  namespaces: ${large-storage-quota_NAMESPACES}
  hard:
    requests.storage: 1024Gi
  
  
  