defaultReplicas: "1"
defaultPort: "8080"
defaultProtocol: "TCP"
defaultLimitsCpu: "200m"
defaultLimitsMemory: "500Mi"
defaultRequestsCpu: "100m"
defaultRequestsMemory: "50Mi"
defaultRollingUpdateMaxSurge: "25%"
defaultRollingUpdateMaxUnavailable: "25%"
