FROM image-registry.openshift-image-registry.svc:5000/openshift/el-cicd-jenkins-agent-base

USER root

RUN yum install -y --disableplugin=subscription-manager --setopt=tsflags=nodocs gcc python3-devel python3-setuptools python3-pip python3-wheel && \
    yum clean all --disableplugin=subscription-manager && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install bzt virtualenv && \
    rm -f /var/logs/*

USER 1001