######################################################################
##
## The following template can be used as is for defining most CronJobs.
## The parameters defined within should allow you to configure a CronJob
## to any degree you need.  With minor exceptions documented below, DO NOT
## edit the template; e.g. you need sidecar container. If you need additional
## parameters, use kustomize and template-defs.json per the el-CICD documention
## to add them.
##
######################################################################
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: cronjob-template
message: Deploying using templated resources
metadata:
  name: cronjob-template
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: ${APP_NAME}
  spec:
    concurrencyPolicy: ${CONCURRENCY_POLICY}
    failedJobsHistoryLimit: ${{FAILED_JOB_HISTORY_LIMIT}}
    jobTemplate:
      metadata:
      spec:
        template:
          metadata:
            labels:
              projectid: ${PROJECT_ID}
              microservice: ${MICROSERVICE_NAME}
              app: ${APP_NAME}
          spec:
            containers:
            - command:
              - ${INTERPRETER}
              - ${EXECUTABLE}
              image: ${IMAGE_REPOSITORY}/${PROJECT_ID}-${MICROSERVICE_NAME}:${IMAGE_TAG}
              imagePullPolicy: ${IMAGE_PULL_POLICY}
              name: ${APP_NAME}
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEM_LIMIT}
                requests:
                  cpu: ${CPU_REQ}
                  memory: ${MEM_REQ}
            imagePullSecrets:
            - name: ${PULL_SECRET}
            dnsPolicy: ${DNS_POLICY}
            restartPolicy: ${RESTART_POLICY}
            securityContext: {}
            terminationGracePeriodSeconds: ${{TERMINATION_GRACE_PERIOD_SECONDS}}
    schedule: ${SCHEDULE}
############################################################################
##
## The schedule is defined as a parameter, and as such will need to be a quoted string; e.g:
##
## '*/10 * * * *'
##
## CronJobs use standard cron notation for scheduling.
##
############################################################################
    successfulJobsHistoryLimit: ${{SUCCESSFUL_JOBS_HISTORY_LIMIT}}
    suspend: ${{SUSPEND}}

parameters:
- description: The image repository from where to fetch the image
  displayName: Image Repository
  name: IMAGE_REPOSITORY
  required: true

- description: The image pull policy
  displayName: Image Pull Policy
  name: IMAGE_PULL_POLICY
  required: true
  value: Always

- description: The image repository pull secret
  displayName: Image Repository Pull
  name: PULL_SECRET
  required: true

- description: The name for the microservice, derived by el-CICD from the name of the Git repository
  displayName: Microservice Name
  name: MICROSERVICE_NAME
  required: true

- description: The name for the app.  Set this value manually through the template-defs.json file for multiple deployments of the same image.
  displayName: Application Name
  name: APP_NAME
  required: true

- description: The Project ID
  displayName: Project ID
  name: PROJECT_ID
  required: true

- description: The name of the environment the image is being deployed to.  Used to help define unique routes.
  displayName: Environment Name
  name: ENV
  required: true

- description: Concurrrency Policy
  displayName:  Concurrrency Policy
  name: CONCURRENCY_POLICY
  required: true
  value: Allow

- description: Failed job history limit
  displayName:  Failed Job History Limit
  name: FAILED_JOB_HISTORY_LIMIT
  required: true
  value: "3"

- description: Image Tag used to pull image from image repository
  displayName:  Image Tag
  name: IMAGE_TAG
  required: true

- description: CPU Resource Request; see OKD docs for more info
  displayName: CPU Resource Request
  name: CPU_REQ
  required: true
  value: 100m

- description: Maximum CPU Resource Limit allowed; see OKD docs for more info
  displayName: CPU Resource Limit
  name: CPU_LIMIT
  required: true
  value: 200m

- description: Memory Resource Request; see OKD docs for more info
  displayName: Memory Resource Request
  name: MEM_REQ
  required: true
  value: 50Mi

- description: Memory Resource Limit (Ceiling) in Mi or Gi; see OKD docs for more info
  displayName: Memory Resource Limit in Mi or Gi
  name: MEM_LIMIT
  required: true
  value: 500Mi

- description: Interpreter program to run 
  displayName: Interpreter program
  name: INTERPRETER
  required: true

- description: Full path to executable program
  displayName: executable program
  name: EXECUTABLE
  required: true

- description: Restart Policy
  displayName: Restart policy
  name: RESTART_POLICY
  required: true
  value: OnFailure

- description: DNS Policy
  displayName: DNS Policy
  name: DNS_POLICY
  required: true
  value: ClusterFirst

- description: Termination grace period in seconds
  displayName: Termination Grace Period Seconds
  name: TERMINATION_GRACE_PERIOD_SECONDS
  required: true
  value: "30"

- description: Cronjob schedule, using standard cron notation
  displayName: Cronjob schedule
  name: SCHEDULE
  required: true

- description: Successful job history limit
  displayName: Successful Job History Limit
  name: SUCCESSFUL_JOBS_HISTORY_LIMIT
  required: true
  value: "3"

- description: Suspend the job from launching
  displayName: Suspend
  name: SUSPEND
  required: true
  value: "false"
