######################################################################
##
## The following template can be used as is for defining an external Route.
## The Host Name will be automatically defined by el-CICD if not specified
## in your template-defs.json.  The default values include port 8080,
## edge termination, and a weight of 100.
##
######################################################################
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: ingress-template
message: Ingress template
metadata:
  name:  ingress-template
objects:
######################################################################
##
## APP_NAME defaults to the microservice name.  You will need to override
## this is you intend to deploy the same image multiple times.
##
######################################################################
- apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    rules:
    - host: ${ROUTE_HOST}
      http:
        paths:
        - path: ${INGRESS_PATH}
          pathType: Prefix
          backend:
            serviceName: ${APP_NAME}
            servicePort: ${{SVC_PORT}}

parameters:
- description: The name for the app; set this value in template-defs.json for multiple deployments of the same image; default value is the microservice name
  displayName: Application Name
  name: APP_NAME
  required: true

- description: |-
    Route hostname; will be set generated by el-CICD if not specified in template-defs.json
    will be automatically modified per SDLC namespace environment for ease of use
  displayName: Route hostname
  name: ROUTE_HOST
  required: true

- description: Relative path after domain
  displayName: Ingress path
  name: INGRESS_PATH
  required: true
  value: "/"

- description: Service port
  displayName: Service Port
  name: SVC_PORT
  required: true
  value: "8080"
