######################################################################
##
## The following template can be used as is for defining an external Route.
## The Host Name will be automatically defined by el-CICD if not specified
## in your template-defs.json.  The default values include port 8080,
## edge termination, and a weight of 100.
##
######################################################################
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: ingress-template
message: Ingress template
metadata:
  name:  ingress-template
objects:
######################################################################
##
## APP_NAME defaults to the microservice name.  You will need to override
## this is you intend to deploy the same image multiple times.
##
######################################################################
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    annotations:
      kubernetes.io/ingress.allow-http: "${ALLOW_HTTP}"
  spec:
    ingressClassName: ${INGRESS_CLASS_NAME}
    rules:
    - host: ${ROUTE_HOST}
      http:
        paths:
        - path: ${INGRESS_PATH}
          pathType: Prefix
          backend:
            service:
              name: ${APP_NAME}
              port:
                number: ${{SVC_PORT}}
  tls:
    - hosts:
      secretName: ${CUSTOM_TLS_SECRET_NAME}

parameters:
- description: The name for the app; set this value in template-defs.json for multiple deployments of the same image; default value is the microservice name
  displayName: Application Name
  name: APP_NAME
  required: true

- description: |-
    Route hostname; will be set generated by el-CICD if not specified in template-defs.json
    will be automatically modified per SDLC namespace environment for ease of use
  displayName: Route hostname
  name: ROUTE_HOST
  required: true

- description: Relative path after domain
  displayName: Ingress path
  name: INGRESS_PATH
  required: true
  value: "/"

- description: Allow HTTP
  displayName: Is HTTP traffic allowed?  Default is no, and redirect to HTTPS will occur
  name: ALLOW_HTTP
  required: true
  value: "false"

- description: Ingress Class Name
  displayName: Ingress Class Name
  name: INGRESS_CLASS_NAME
  required: true
  value: "default"

- description: Service port
  displayName: Service Port
  name: SVC_PORT
  required: true
  value: "8080"

- description: Custom TLS Secret Name
  displayName: Custom TLS Secret Name
  name: CUSTOM_TLS_SECRET_NAME
