apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: nfs-pv-template
message: Deploying using templated resources
metadata:
  name:  nfs-pv-template
objects:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: ${PV_NAME}
  spec:
    capacity:
      storage: ${CAPACITY}
    accessModes:
      - ${ACCESS_MODE}
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: ${NFS_EXPORT}
      server: ${NFS_SERVER}
    claimRef:
      name: ${CLAIM_NAME}
      namespace: ${NAMESPACE}

parameters:
- description: Persistent Volume Object Name
  displayName: Persistent Volume Object Name
  name: PV_NAME
  required: true

- description: Storage Capacity using Mi for megabytes, or Gi for gigabytes
  displayName: Storage Capacity
  name: CAPACITY
  required: true

- description: Storage Access Mode "ReadWriteOnce|ReadWriteMany|ReadOnly"
  displayName: Storage Access Mode
  name: ACCESS_MODE
  required: true

- description: NFS Export path
  displayName: NFS Export path 
  name: NFS_EXPORT
  required: true

- description: NFS Server hostname or IP address
  displayName: NFS Server hostname or IP address
  name: NFS_SERVER
  required: true

- description: Persistent Volume Claim Name
  displayName: Persistent Volume Claim Name
  name: CLAIM_NAME
  required: true

- description: Namespace Name
  displayName: Namespace Name
  name: NAMESPACE
  required: true