elCicdTemplates-resourceQuotas:
- templateName: resourceQuota
  objName: small-mem-quota
  mustHaveAnyProfile:
  - small-mem-quota
  namespaces: $<small-mem-quota_NAMESPACES>
  hard:
    limits.memory: 12Gi
  scopes:
  - NotTerminating

- templateName: limitRange
  objName: small-mem-limit
  mustHaveAnyProfile:
  - small-mem-limit
  namespaces: $<small-mem-limit_NAMESPACES>
  limits:
  - default:
      memory: 256Mi
    max:
      memory: 1Gi
    defaultRequest:
      memory: 50Mi
      cpu: 150m
    type: Container

- templateName: resourceQuota
  objName: small-storage-quota
  mustHaveAnyProfile:
  - small-storage-quota
  namespaces: $<small-storage-quota_NAMESPACES>
  hard:
    requests.storage: 24Gi

- templateName: resourceQuota
  objName: medium-mem-quota
  mustHaveAnyProfile:
  - medium-mem-quota
  namespaces: $<medium-mem-quota_NAMESPACES>
  hard:
    limits.memory: 48Gi
  scopes:
  - NotTerminating

- templateName: limitRange
  objName: medium-mem-limit
  mustHaveAnyProfile:
  - medium-mem-limit
  namespaces: $<medium-mem-limit_NAMESPACES>
  limits:
  - default:
      memory: 512Mi
    max:
      memory: 2Gi
    defaultRequest:
      memory: 50Mi
      cpu: 150m
    type: Container

- templateName: resourceQuota
  objName: medium-storage-quota
  mustHaveAnyProfile:
  - medium-storage-quota
  namespaces: $<medium-storage-quota_NAMESPACES>
  hard:
    requests.storage: 256Gi

- templateName: resourceQuota
  objName: large-mem-quota
  mustHaveAnyProfile:
  - large-mem-quota
  namespaces: $<large-mem-quota_NAMESPACES>
  hard:
    limits.memory: 96Gi
  scopes:
  - NotTerminating

- templateName: limitRange
  objName: large-mem-limit
  mustHaveAnyProfile:
  - large-mem-limit
  namespaces: $<large-mem-limit_NAMESPACES>
  limits:
  - default:
      memory: 1Gi
    max:
      memory: 4Gi
    defaultRequest:
      memory: 50Mi
      cpu: 150m
    type: Container

- templateName: resourceQuota
  objName: large-storage-quota
  mustHaveAnyProfile:
  - large-storage-quota
  namespaces: $<large-storage-quota_NAMESPACES>
  hard:
    requests.storage: 1024Gi
  
  
  