FROM openshift/jenkins-slave-maven-centos7:v3.11

USER root

RUN yum-config-manager --disable cbs-paas7-openshift-multiarch-el7-build && \
    yum remove git && \
    yum install --setopt=tsflags=nodocs deltarpm -y && \
    yum install -y --setopt=tsflags=nodocs epel-release && \
    yum install -y https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm && \
    yum install -y --setopt=tsflags=nodocs podman skopeo buildah jq git && \
    yum update -y --setopt=tsflags=nodocs && \
    yum  clean all && \
    curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash -s 3.8.5 && \
    mv ./kustomize /usr/local/bin

USER 1001