{{- $skippedList := list }}
{{- range $templateValues := .Values.templates }}
  {{- $_ := set $templateValues "appName" ($templateValues.appName | default $.Values.microService) }}
  {{ $render := true }}
  {{- if $templateValues.forProfiles }}
    {{- range $profile := $templateValues.forProfiles }}
      {{- $render = and $render (has $profile $.Values.profiles) }}
    {{- end }}
  {{- end }}
  {{- if and $render $templateValues.notProfiles }}
    {{- range $profile := $templateValues.notProfiles }}
      {{- $render = and $render (not (has $profile $.Values.profiles)) }}
    {{- end }}
  {{- end }}
  {{- $templateName := printf "elCicdChart.%s" $templateValues.templateName }}
  {{- if $render }}
    {{- range $profile := $.Values.profiles }}
      {{- include "elCicdChart.mergeProfile" (list $ $templateValues $profile) }}
    {{- end}}
        
    {{- include $templateName (list $ $templateValues) }}
  {{- else }}
    {{- $skippedList = append $skippedList (list $templateValues.templateName $templateValues.appName) }}
  {{- end}}
{{- end }}
---

---
# Profiles: {{ $.Values.profiles }}
{{- range $skipped := $skippedList }}
  {{- include "elCicdChart.skippedTemplate" $skipped }}
{{- end }}

{{ define "elCicdChart.skippedTemplate" }}
# EXCLUDED BY PROFILES: {{ index . 0 }} -> {{ index . 1 }}
{{- end }}