{{- $skippedList := list }}
{{- $_ := set $.Values "templates" ($.Values.templates | default dict) }}
{{- include "elCicdChart.processProfiles" $ }}
{{- range $templateValues := .Values.templates }}
  {{- $_ := $templateValues "extraAnnotationTemplates" list }}
  {{- $_ := set $templateValues "appName" ($templateValues.appName | default $.Values.microService) }}
  {{ $render := true }}
  {{- if $templateValues.forProfiles }}
    {{- range $profile := $templateValues.forProfiles }}
      {{- $render = and $render (has $profile $.Values.profiles) }}
    {{- end }}
  {{- end }}
  {{- if and $render $templateValues.notProfiles }}
    {{- range $profile := $templateValues.notProfiles }}
      {{- $render = and $render (not (has $profile $.Values.profiles)) }}
    {{- end }}
  {{- end }}
  {{- if $render }}
    {{- $templateName := printf "elCicdChart.%s" $templateValues.templateName }}        
    {{- include $templateName (list $ $templateValues) }}
  {{- else }}
    {{- $skippedList = append $skippedList (list $templateValues.templateName $templateValues.appName) }}
  {{- end}}
{{- end }}
{{- if $.Values.microService }}
 {{- include "elCicdChart.microServiceMetaInfo" . }}
{{- end }}
---
# Profiles: {{ $.Values.profiles }}
{{- range $skipped := $skippedList }}
  {{- include "elCicdChart.skippedTemplate" $skipped }}
{{- end }}