elCicdTemplates-resourcequotas:
- templateName: resourceQuota
  appName: small-cpu-mem
  anyProfiles:
  - small-cpu-mem
  namespaces: ${small-cpu-mem_NAMESPACES}
  hard:
    limits.cpu: "4"
    limits.memory: 10Gi
  scopes:
  - NotTerminating

- templateName: resourceQuota
  appName: small-storage
  anyProfiles:
  - small-storage
  namespaces: ${small-storage_NAMESPACES}
  hard:
    requests.storage: 25Gi
    
- templateName: resourceQuota
  appName: medium-cpu-mem
  anyProfiles:
  - medium-cpu-mem
  namespaces: ${medium-cpu-mem_NAMESPACES}
  hard:
    limits.cpu: "8"
    limits.memory: 48Gi
  scopes:
  - NotTerminating
    
- templateName: limitRange
  appName: medium-cpu-range
  anyProfiles:
  - medium-cpu-mem
  namespaces: ${medium-cpu-mem_NAMESPACES}
  limits:
  - default:
      cpu: "8"
    type: Container
  
- templateName: resourceQuota
  appName: medium-storage
  anyProfiles:
  - medium-storage
  namespaces: ${medium-storage_NAMESPACES}
  hard:
    requests.storage: 256Gi
    
- templateName: resourceQuota
  appName: large-cpu-mem
  anyProfiles:
  - large-cpu-mem
  namespaces: ${large-cpu-mem_NAMESPACES}
  hard:
    limits.cpu: "16"
    limits.memory: 95Gi
  scopes:
  - NotTerminating

- templateName: resourceQuota
  appName: large-storage
  anyProfiles:
  - large-storage
  namespaces: ${large-storage_NAMESPACES}
  hard:
    requests.storage: 1024Gi
  
  
  